name: Lint Code Base

on: pull_request

permissions: read-all

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter@v8.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_BASH: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: "tests/data.*"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
